### ISSUE TITLE
Create the Business Owner page

### ISSUE THREAD

**Issue by gadamsatti** [buildor-org/kart-admin#41]

**Comment by Satishpokala124** [comment]
![Image](https://github.com/buildor-org/kart-admin/assets/49762924/cf2b3a61-97a6-4572-92cd-737059131291)

**Comment by Satishpokala124** [comment]
#43 

![Image](https://github.com/buildor-org/kart-admin/assets/49762924/ce216bd0-b18a-4e16-9532-faf53502a75b)

**Comment by gadamsatti** [comment]
Created the base page
